export enum Tool {
  BENDY_LINE = 'BendyLine',
  BRUSH = 'Brush',
  BUCKET = 'Bucket',
  CIRCLE = 'Circle',
  COLOR_PICKER = 'ColorPicker',
  ERASER = 'Eraser',
  LINE = 'Line',
  MAGNIFYING_GLASS = 'MagnifyingGlass',
  MULTI_LINE = 'MultiLine',
  OVAL = 'Oval',
  PENCIL = 'Pencil',
  RECTANGLE = 'Rectangle',
  SELECT_LASSO = 'SelectLasso',
  SELECT_RECTANGLE = 'SelectRectangle',
  SPRAY_CAN = 'SprayCan',
  TEXT = 'Text',
}
